TAP_DANCE_ENABLE = yes
MOUSEKEY_ENABLE  = yes # Mouse keys(+4700)
EXTRAKEY_ENABLE  = yes # Audio control and System control(+450)
CONSOLE_ENABLE   = no  # Console for debug(+400)

ifndef QUANTUM_DIR
	include ../../../../Makefile
endif
